version: '3'

services:
  db:
    image: postgres
    volumes:
      - "./docker/data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB = test
      - POSTGRES_USER = test
      - POSTGRES_PASSWORD = test1234
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    volumes:
      - "./web:/code/web"
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_DB = test
      - POSTGRES_USER = test
      - POSTGRES_PASSWORD = test1234
